name: "CI"

on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test:
    name: CI/CD Test
    # https://github.com/actions/virtual-environments/
    runs-on: ubuntu-24.04
    steps:
      - name: 🛎️ Checkout
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6
      - name: 🌡️ Test
        run: shellcheck *.sh
